# Generates a C++ translation unit containing every migrations/*.sql file, so a
# deployed TRACE binary can create or upgrade a database with no loose SQL.
#
#   cmake -DMIGRATIONS_DIR=<dir> -DOUTPUT_FILE=<file> -P embed_migrations.cmake

if(NOT DEFINED MIGRATIONS_DIR OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "MIGRATIONS_DIR and OUTPUT_FILE are required")
endif()

file(GLOB migration_files "${MIGRATIONS_DIR}/*.sql")
list(SORT migration_files)

set(body "// Generated by scripts/embed_migrations.cmake — do not edit by hand.\n")
string(APPEND body "// Source: migrations/*.sql\n\n")
string(APPEND body "#include \"core/database/migrations.h\"\n\n")
string(APPEND body "namespace trace {\n\n")
string(APPEND body "const std::vector<Migration>& embeddedMigrations() {\n")
string(APPEND body "    static const std::vector<Migration> kMigrations = {\n")

foreach(migration_file IN LISTS migration_files)
    get_filename_component(migration_name "${migration_file}" NAME)
    if(NOT migration_name MATCHES "^([0-9]+)_.*\\.sql$")
        message(FATAL_ERROR "Migration '${migration_name}' must be named <version>_<description>.sql")
    endif()
    set(version "${CMAKE_MATCH_1}")
    # Strip leading zeros so 0001 becomes the integer 1.
    string(REGEX REPLACE "^0+([0-9])" "\\1" version "${version}")

    file(READ "${migration_file}" sql)
    if(sql MATCHES "\\)TRACE_SQL\"")
        message(FATAL_ERROR "Migration '${migration_name}' contains the raw-string delimiter")
    endif()
    string(APPEND body "        Migration{${version}, \"${migration_name}\",\n")
    string(APPEND body "                  R\"TRACE_SQL(${sql})TRACE_SQL\"},\n")
endforeach()

string(APPEND body "    };\n    return kMigrations;\n}\n\n")
string(APPEND body "}  // namespace trace\n")

set(temp_file "${OUTPUT_FILE}.tmp")
file(WRITE "${temp_file}" "${body}")
execute_process(COMMAND ${CMAKE_COMMAND} -E copy_if_different "${temp_file}" "${OUTPUT_FILE}")
file(REMOVE "${temp_file}")
